volumes:
  dev-db-volume: {}
services:
  dev-pg:
    container_name: dbpg
    image: bitnami/postgresql:17.0.0
    environment:
      POSTGRESQL_DATABASE: lab1
      POSTGRESQL_USERNAME: eoeqs
      POSTGRESQL_PASSWORD: jacwhiel7337
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'

