volumes:
  dev-db-volume: {}
services:
  dev-pg:
    container_name: dbpg
    hostname: lala
    image: bitnami/postgresql:17.0.0
    environment:
      POSTGRESQL_DATABASE: lab1
      POSTGRESQL_USERNAME: eoeqs
      POSTGRESQL_PASSWORD: eoeqs
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:

    container_name: back_app
    hostname: bbb
    depends_on:
      dev-pg:
         condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080:8080'

  frontend:
    container_name: front_app
    depends_on:
      - backend
    build:
      context: auth-app
      dockerfile: Dockerfile

    ports:
      - '8686:80'