server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://lala:5432/lab1
    username: eoeqs
    password: eoeqs
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org:
#      springframework: trace
#
#
